name: Bundle App For Production
on:
  push:
    branches: "main"

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Files
        uses: actions/checkout@v4
      - name: Build project
        run: |
          npm install --save-dev
          npm run build
      - name: Release build
        run: |
          git config --global user.name "John Delvin"
          git config --global user.email "johndelvin51@gmail.com"
          git config --global --add safe.directory $(pwd)
          git add ./dist
          git commit -m "upload build"
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TK }}
          branch: ${{ github.ref }}
